version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: rag_pg
    environment:
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpass
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    container_name: rag_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db